import { ExperienceItem, EducationItem, PublicationItem, SkillCategory } from './types';

export const EXPERIENCES: ExperienceItem[] = [
  {
    id: 'daiichi-sankyo',
    role: 'Associate Director, Bioinformatics – Translational Bioinformatics',
    company: 'Daiichi Sankyo Inc',
    location: 'Basking Ridge, NJ',
    period: 'Oct 2022 – Present',
    bullets: [
      'Summarize gene alterations in a clear and concise format, highlighting their functional roles in clinical oncology to determine response or resistance to Daiichi Sankyo’s investigational study drugs.',
      'Partner closely with Clinical Biostatistics and Programming teams to apply necessary coding, software development, and statistical analyses to large clinical oncology datasets.',
      'Provide core bioinformatic support and direction for the design of clinical correlative studies involving novel biomarker identification.'
    ]
  },
  {
    id: 'prelude-ad',
    role: 'Associate Director, Bioinformatics – Translational Medicine',
    company: 'Prelude Therapeutics',
    location: 'Wilmington, DE',
    period: 'Jan 2022 – Oct 2022',
    bullets: [
      'Led clinical bioinformatics trials, focusing on the processing, analysis, and annotation of high-throughput NGS (DNA-seq and RNA-seq) datasets generated by third-party CROs and vendors.',
      'Synthesized complex gene alterations and clinical markers into high-impact reports regarding drug sensitivity and drug resistance mechanisms.',
      'Collaborated with Biostatistics and Programming to integrate genomic biomarkers into clinical protocols.',
      'Designed, constructed, and managed expansive biomarker databases in alignment with internal IT and Discovery teams to expose key gene signatures.',
      'Identified, evaluated, and managed strategic relationships with external vendors for genomic biomarker testing in clinical programs.'
    ]
  },
  {
    id: 'prelude-ps',
    role: 'Principal Scientist – Bioinformatics',
    company: 'Prelude Therapeutics',
    location: 'Wilmington, DE',
    period: 'Nov 2019 – Jan 2022',
    bullets: [
      'Executed translational bioinformatics strategies to support the identification of predictive genomic markers for ongoing clinical studies (PRT543, PRT811, and PRT1419 programs).',
      'Conducted extensive exploratory data analysis using public cancer genomics and transcriptomics datasets (TCGA, CCLE, at-scale cohorts) to aid early-stage drug design and preclinical validation.',
      'Established in-house robust analysis pipelines for RNA-seq, DNA-seq, ChIP-seq, and ATAC-seq data using state-of-the-art variant annotation and variant calling tools.',
      'Managed vendor quality control assays for external NGS workflows and coordinated cross-functional research milestones.'
    ]
  },
  {
    id: 'cancer-genetics-lead',
    role: 'Lead – Bioinformatics',
    company: 'Cancer Genetics Inc.',
    location: 'Rutherford, NJ',
    period: 'Jul 2016 – Sep 2019',
    bullets: [
      'Managed and provided leadership to a collaborative team of bioinformaticians, developers, and statistical modelers in a CLIA-certified clinical diagnostics environment.',
      'Pioneered assay-based molecular stratification methods for clinical decision-making, using patient outcomes to advance personalized oncology approaches.',
      'Led major clinical research initiatives looking at genomic imbalances and epigenetic markers, discovering novel prognostic biomarkers in hematological (CLL, DLBCL, FL, MCL, Myeloma) and solid tumors (Renal Cell Carcinoma).',
      'Oversaw CLI/GUI informatics pipeline reviews, serving as a key molecular interpreter and member of the molecular tumor board.',
      'Successfully commercialized several somatic (Myeloid, Lymphoid, Oncomine, Renal) and hereditary diagnostic targeted panels through validations leading to NY State CLEP approvals.',
      'Developed advanced workflows evaluating advanced immuno-oncology markers such as Tumor Mutational Burden (TMB), neo-antigens, and T-Cell Receptor (TCR) clonality.',
      'Maintained deep collaborations with leading clinical institutions including MSKCC, Mount Sinai, and USC.'
    ]
  },
  {
    id: 'cancer-genetics-senior',
    role: 'Senior Scientist – Bioinformatics',
    company: 'Cancer Genetics Inc.',
    location: 'Rutherford, NJ',
    period: 'Oct 2011 – Jun 2016',
    bullets: [
      'Constructed robust clinical-grade NGS pipelines (DNA-seq, RNA-seq) utilising GATK best practices and open-source packages (BWA, Picard, Samtools, Bedtools, GATK4, FreeBayes, CBS, GISTIC).',
      'Developed modular packages for genomic copy-number anomaly detection and integrated upstream variant filters with survival analysis algorithms.',
      'Built automated data quality control Dashboards for high-throughput laboratory sequence processing.'
    ]
  },
  {
    id: 'mskcc-postdoc',
    role: 'Postdoctoral Research Associate',
    company: 'Memorial Sloan-Kettering Cancer Center (MSKCC)',
    location: 'New York, NY',
    period: 'Oct 2008 – Oct 2011',
    bullets: [
      'Developed clinical biomarker assays for predicting therapeutic response to Sunitinib by undertaking deep expression profiling of an extensive Renal Cell Carcinoma (RCC) patient cohort.',
      'Discovered biomarkers for HIF-dependent and HIF-independent RCC via high-resolution transcriptomic profiling of 200+ kidney cancer trial cases.',
      'Integrated genomic copy number variation, micro-RNA abundance, and DNA methylation data with gene expression profiles to uncover regulatory loops.',
      'Elucidated microRNA networks (such as miR-18b and miR-518b regulating FOXN1) active during epidermal lineage differentiation of pluripotent cells.',
      'Constructed ChIP-seq and ChIP-on-chip analytical workflows to map transcription factor maps in Germinal Center Carcinoma (GCC) using Bioconductor.'
    ]
  },
  {
    id: 'usm-gra',
    role: 'Graduate Research Associate',
    company: 'University of Southern Mississippi',
    location: 'Hattiesburg, MS',
    period: '2004 – Oct 2008',
    bullets: [
      'Conducted advanced machine learning analyses of microarray gene expression data for diagnostic, prognostic, and clinical drug response applications.',
      'Participated directly in the MicroArray Quality Control (MAQC-II) multi-site project initiated by the U.S. Food and Drug Administration (FDA).'
    ]
  }
];

export const EDUCATION: EducationItem[] = [
  {
    degree: 'Ph.D.',
    field: 'Bioinformatics',
    institution: 'University of Southern Mississippi',
    location: 'Hattiesburg, MS',
    period: '2004 – Oct 2008',
    details: 'Dissertation: Knowledge-based analysis of microarray gene expression data by using machine learning algorithms for diagnostic, prognostic, or therapeutic applications (MAQC-II / FDA Research Partnership).'
  },
  {
    degree: 'M.Tech.',
    field: 'Biotechnology',
    institution: 'Jawaharlal Nehru Technological University',
    location: 'Hyderabad, India',
    period: '1999 – 2002',
    details: 'Thesis: Homology protein modeling of nitroreductase from Helicobacter pylori and VPX protein from Simian Immunodeficiency Virus (SIV).'
  }
];

export const SKILLS: SkillCategory[] = [
  {
    title: 'Translational Bioinformatics & Genomics',
    skills: [
      { name: 'Oncology Therapeutics & Drug Response', level: 'Expert', iconName: 'Dna' },
      { name: 'NGS (DNA-seq, RNA-seq, ChIP-seq, ATAC-seq)', level: 'Expert', iconName: 'Dna' },
      { name: 'Immuno-Oncology (TMB, TCR, Neo-antigen)', level: 'Expert', iconName: 'ShieldAlert' },
      { name: 'Onco-panels & Diagnostics (CLEP Validations)', level: 'Expert', iconName: 'Activity' },
      { name: 'Biomarker Discovery & Stratification', level: 'Expert', iconName: 'SearchCode' },
      { name: 'Multi-omics Data Integration (TCGA, COSMIC)', level: 'Expert', iconName: 'Database' }
    ]
  },
  {
    title: 'Pipelines & Computational Methods',
    skills: [
      { name: 'GATK Best Practices & Variant Calling', level: 'Expert', iconName: 'Workflow' },
      { name: 'Sequence Alignment (BWA, Bowtie, STAR)', level: 'Expert', iconName: 'GitCommit' },
      { name: 'CNA Analysis (CBS, GISTIC, CNVkit)', level: 'Expert', iconName: 'BarChart3' },
      { name: 'Quality Control (FastQC, Picard, Samtools)', level: 'Expert', iconName: 'CheckCircle2' }
    ]
  },
  {
    title: 'Systems & Software',
    skills: [
      { name: 'Python (Pandas, NumPy, Scikit-learn)', level: 'Expert', iconName: 'Code' },
      { name: 'R & Bioconductor Packages', level: 'Expert', iconName: 'Binary' },
      { name: 'Cloud Computing (AWS EC2, S3, Genomics Batch)', level: 'Advanced', iconName: 'Cloud' },
      { name: 'Genome Browsers (UCSC, IGV, Circos)', level: 'Expert', iconName: 'Eye' },
      { name: 'Relational/Functional Bio-Databases', level: 'Expert', iconName: 'Server' }
    ]
  },
  {
    title: 'Statistical & Clinical Analytics',
    skills: [
      { name: 'Survival Analysis (Kaplan-Meier, Cox Proportional Hazards)', level: 'Expert', iconName: 'AreaChart' },
      { name: 'Univariate & Multivariate Regression', level: 'Expert', iconName: 'LineChart' },
      { name: 'Machine Learning Classification', level: 'Expert', iconName: 'Cpu' },
      { name: 'Clinical Biostatistics Collaboration', level: 'Expert', iconName: 'Users' }
    ]
  }
];

export const PUBLICATIONS: PublicationItem[] = [
  {
    id: 'pub1',
    authors: 'Carter J, Hulse M, Sivakumar M, Burtell J, Thodima V, Wang M, et al.',
    title: 'PRMT5 inhibitors regulate DNA damage repair pathways in cancer cells and improve response to PARP inhibition and chemotherapies',
    journal: 'Cancer Res Commun',
    year: 2023,
    dateStr: 'Nov 2023',
    link: 'https://pubmed.ncbi.nlm.nih.gov/37930107/'
  },
  {
    id: 'pub2',
    authors: 'Deveson IW, Gong B, Lai K, LoCoco JS, Richmond TA, Schageman J, Thodima V, et al.',
    title: 'Evaluating the analytical validity of circulating tumor DNA sequencing assays for precision oncology',
    journal: 'Nature Biotechnol',
    year: 2021,
    dateStr: 'Sep 2021',
    link: 'https://www.nature.com/articles/s41587-021-00945-w'
  },
  {
    id: 'pub3',
    authors: 'Gong B, Li D, Kusko R, Novoradovskaya N, Zhang Y, Wang S, Thodima V, et al.',
    title: 'Cross-oncopanel study reveals high sensitivity and accuracy with overall analytical performance depending on genomic regions',
    journal: 'Genome Biol',
    year: 2021,
    dateStr: 'Apr 2021',
    link: 'https://genomebiology.biomedcentral.com/articles/10.1186/s13059-021-02315-w'
  },
  {
    id: 'pub4',
    authors: 'Stenehjem DD, Hahn AW, Gill DM, Albertson D, Gowrishankar B, Merriman J, Agarwal AM, Thodima V, Harrington EB, Au TH, Maughan BL, Houldsworth J, Pal SK, Agarwal N.',
    title: 'Predictive genomic markers of response to VEGF targeted therapy in metastatic renal cell carcinoma',
    journal: 'PLoS One',
    year: 2019,
    dateStr: 'Jan 2019',
    link: 'https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0211296'
  },
  {
    id: 'pub5',
    authors: 'Kushwaha R, Jagadish N, Kustagi M, Mendiratta G, Seandel M, Soni R, Korkola JE, Thodima V, Califano A, Bosl GJ, Chaganti RS.',
    title: 'Mechanism and Role of SOX2 Repression in Seminoma: Relevance to Human Germline Specification',
    journal: 'Stem Cell Reports',
    year: 2016,
    dateStr: 'May 2016',
    link: 'https://www.cell.com/stem-cell-reports/fulltext/S2213-6711(16)30036-7'
  },
  {
    id: 'pub6',
    authors: 'Siddiqi I, Friedman J, Barry-Holson K, Ma C, Thodima V, Kang I, Padmanabhan R, Dias L, Kelly K, Brynes R, Kamalakaran S, Houldsworth J.',
    title: 'Characterization of a variant of t(14;18) negative nodal diffuse follicular lymphoma with CD23 expression, 1p36/TNFRSF14 abnormalities, and STAT6 mutations',
    journal: 'Modern Pathology',
    year: 2016,
    dateStr: 'Jun 2016',
    link: 'https://www.nature.com/articles/modpathol201659'
  },
  {
    id: 'pub7',
    authors: 'Dias LM, Thodima V, Friedman J, Ma C, Guttapalli A, Mendiratta G, Siddiqi IN, Syrbu S, Chaganti RS, Houldsworth J.',
    title: 'Cross-platform assessment of genomic imbalance confirms the clinical relevance of genomic complexity and reveals loci with potential pathogenic roles in diffuse large B-cell lymphoma',
    journal: 'Leuk Lymphoma',
    year: 2016,
    dateStr: 'Apr 2016',
    link: 'https://www.tandfonline.com/doi/abs/10.3109/10428194.2015.1075677'
  },
  {
    id: 'pub8',
    authors: 'Kushwaha R, Thodima V, Tomishima MJ, Bosl GJ, Chaganti R.',
    title: 'Mir-18 and mir-518b target FOXN1 during epithelial lineage differentiation in pluripotent cells',
    journal: 'Stem Cells Dev',
    year: 2014,
    dateStr: 'May 2014',
    link: 'https://www.liebertpub.com/doi/10.1089/scd.2013.0487'
  },
  {
    id: 'pub9',
    authors: 'Houldsworth J, Guttapalli A, Thodima V, et al.',
    title: 'Genomic Imbalance Defines Three Prognostic Groups for Risk Stratification of Chronic Lymphocytic Leukemia Patients',
    journal: 'Leuk Lymphoma',
    year: 2014,
    dateStr: 'Apr 2014',
    link: 'https://www.tandfonline.com/doi/abs/10.3109/10428194.2013.821617'
  },
  {
    id: 'pub10',
    authors: 'Lopez-Lago MA, Posner S, Thodima VJ, Molina AM, Motzer RJ, Chaganti RS.',
    title: 'Neutrophil chemokines secreted by tumor cells mount a lung antimetastatic response during renal cell carcinoma progression',
    journal: 'Oncogene',
    year: 2013,
    dateStr: 'Apr 2013',
    link: 'https://www.nature.com/articles/onc2012189'
  },
  {
    id: 'pub11',
    authors: 'López-Lago M, Thodima V, Guttapalli A, Chan T, Heguy A, Molina A, Reuter V, Motzer R, Chaganti RSK.',
    title: 'Genomic Deregulation during Metastasis of Renal Cell Carcinoma Implements a Myofibroblast-Like Program of Gene Expression',
    journal: 'Cancer Research',
    year: 2010,
    dateStr: 'Nov 2010',
    link: 'https://aacrjournals.org/cancerres/article/70/23/9682/560738/Genomic-Deregulation-during-Metasis-of-Renal'
  },
  {
    id: 'pub12',
    authors: 'Shi L, Campbell G, Jones WD, Campagne F, ... , Thodima V, Trygg J, Vishnuvajjala L, Wang SJ, Wu J, Wu Y, Xie Q, Yousef WA, Zhang L, ... , MAQC Consortium.',
    title: 'The MicroArray Quality Control (MAQC)-II study of common practices for the development and validation of microarray-based predictive models',
    journal: 'Nature Biotechnology',
    year: 2010,
    dateStr: 'Aug 2010',
    link: 'https://www.nature.com/articles/nbt.1665'
  },
  {
    id: 'pub13',
    authors: 'Majji S., Thodima V., Sample R., Whitley D., Deng Y., Mao J., and Chinchar V. G.',
    title: 'Transcriptome analysis of Frog Virus 3, the type species of the genus Ranavirus, family Iridoviridae',
    journal: 'Virology',
    year: 2009,
    dateStr: 'Aug 2009',
    link: 'https://pubmed.ncbi.nlm.nih.gov/19541334/'
  },
  {
    id: 'pub14',
    authors: 'Milev-Milovanovic I, Majji S, Thodima V, Deng Y, Hanson L, Arnizaut A, Waldbieser G, Chinchar VG.',
    title: 'Identification and expression analyses of poly [I:C]-stimulated genes in channel catfish (Ictalurus punctatus)',
    journal: 'Fish Shellfish Immunol',
    year: 2009,
    dateStr: 'May 2009',
    link: 'https://pubmed.ncbi.nlm.nih.gov/19176251/'
  },
  {
    id: 'pub15',
    authors: 'Majji S., Thodima V., Arnizaut A., Deng Y., May, W., Sittman D., Hanson L., and Chinchar V. G.',
    title: 'Transcriptional Profiles of Cloned Channel Catfish (Ictalurus punctatus) Lymphoid Cell Lines',
    journal: 'Dev Comp Immunol',
    year: 2009,
    dateStr: 'Feb 2009',
    link: 'https://pubmed.ncbi.nlm.nih.gov/18817812/'
  },
  {
    id: 'pub16',
    authors: 'Deng Y, Dong Y, Thodima V, Clem RJ, Passarelli L.',
    title: 'Analysis and functional annotation of expressed sequence tags from the fall armyworm Spodoptera frugiperda',
    journal: 'BMC Genomics',
    year: 2006,
    dateStr: 'Oct 2006',
    link: 'https://bmcgenomics.biomedcentral.com/articles/10.1186/1471-2164-7-264'
  },
  {
    id: 'pub17',
    authors: 'Thodima V, Pirooznia M, Deng Y.',
    title: 'RiboaptDB: A Comprehensive Database of Ribozymes and Aptamers',
    journal: 'BMC Bioinformatics',
    year: 2006,
    dateStr: 'Sep 2006',
    link: 'https://bmcbioinformatics.biomedcentral.com/articles/10.1186/1471-2105-7-S2-S6'
  }
];

export const PROJECTS = [
  {
    title: 'Precision Oncology Assay Validation (CLEP Panels)',
    description: 'Pioneered clinical validations and analytical validation study designs for somatic and hereditary cancer diagnostic panels, receiving high-complexity NY State Clinical Laboratory Evaluation Program (CLEP) approvals.',
    impact: 'Implemented 6+ CLIA diagnostic assays used in commercial laboratories to stratify oncology treatments.',
    tags: ['Clinical Diagnostics', 'NGS', 'NY CLEP', 'Somatic Mutation Panels']
  },
  {
    title: 'FDA MicroArray Quality Control (MAQC-II)',
    description: 'Consortium initiative to establish common standards, cross-site reproducibility, and machine learning guidelines for microarrays and genomic biomarkers, serving as a core pipeline contributor and researcher.',
    impact: 'Established gold-standard evaluation protocols for genomic classifier algorithms in oncology trials.',
    tags: ['Machine Learning', 'Regulatory Science', 'Biomarkers', 'Microarray Consortium']
  },
  {
    title: 'Translational Bioinformatics & Biomarker Discovery Platforms',
    description: 'Constructed custom micro-services to link transcriptomic (RNA-seq), genomic (DNA-seq, copy number variants) and epigenetic datasets across in-house and public platforms (TCGA, CCLE, Cosmic) to fast-track target discovery.',
    impact: 'Directly supported molecular stratification criteria for Phase I/II investigative targets (PRT543, PRT811, PRT1419 programs).',
    tags: ['Pipelines', 'High Performance Computing', 'TCGA Integration', 'Onco-targets']
  }
];
